### PR TITLE
Update Serializer.hpp

### PR DESCRIPTION
**Pull request by qihang518887**

### CODE REVIEW

**Comment by ghost** [comment]
We explicitly disallow `peer` here. For more information, see https://github.com/Qv2ray/QvPlugin-Trojan/issues/14 , https://github.com/Qv2ray/Qv2ray/issues/844 and https://github.com/v2board/v2board/pull/295

**Comment by ghost** [comment]
It's better to notify the deprecated `peer` has been used so please add a log.

**Comment by qihang518887** [comment]
Sure!

**Comment by qihang518887** [comment]
Sure!

**Comment by qihang518887** [comment]
But, how to print log...
I am not familiar with this.

**Comment by ghost** [comment]
`qDebug()` should work

**Comment by qihang518887** [comment]
like this？

**Pull request merged**
